// Build-time only. Embed WASM so the host bundle needs no runtime asset path or native addon.
import { createRequire } from "node:module";
import { readFile, mkdir, writeFile } from "node:fs/promises";
const require = createRequire(import.meta.url);
const bytes = await readFile(require.resolve("@resvg/resvg-wasm/index_bg.wasm"));
await mkdir(new URL("./generated/", import.meta.url), { recursive: true });
await writeFile(new URL("./generated/wasm.ts", import.meta.url),
  "// GENERATED by npm run prepare:wasm; do not commit.\nexport const wasmBase64 = " + JSON.stringify(bytes.toString("base64")) + ";\n");
console.log("Embedded resvg WASM:", bytes.length, "bytes");
